LOG_INFO "Fixing Wifi.."
REMOVE "vendor" "bin/hw/wpa_supplicant"
REMOVE "vendor" "bin/hw/vendor.samsung.hardware.wifi@2.0-service"
REMOVE "vendor" "bin/hw/android.hardware.wifi@1.0-service"
REMOVE "vendor" "bin/hw/wpa_supplicant"
REMOVE "vendor" "bin/hw/vendor.samsung.hardware.wifi@2.0-service"
REMOVE "vendor" "bin/hw/android.hardware.wifi@1.0-service"

ADD_FROM_FW "dm3q" "vendor" "bin/hw/wpa_supplicant"
ADD_FROM_FW "dm3q" "vendor" "bin/hw/vendor.samsung.hardware.wifi@2.0-service"
ADD_FROM_FW "dm3q" "vendor" "bin/hw/android.hardware.wifi@1.0-service"
